### ISSUE TITLE
[FR] Add pre-commit configuration and documentation

### ISSUE THREAD

**Issue by see7e** [see7e/github-templates#3]
### Feature description

Add generalist configuration for pre-commit hook.

### Possible Implementation

```yaml
---
# Globals
exclude: >
  ^(
    docs/|
    \.git/|
    \.github/.*|
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
        description: "Removes trailing whitespace"
      - id: end-of-file-fixer
        description: "Ensures files end with a newline"
      - id: check-added-large-files
        description: "Prevent large files from being added to the repo"
        args: ["--maxkb=500"]
        exclude: >
          ^docs/|
          ^\.git/|
          ^\.github/.*|

   - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        description: "Lints YAML files"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
        description: "Prevent committing private keys"
```
